Lc 15 : Added photo functionality to user-card
Planet-NULLCAST/linkedin-clone pull request #19
Opened 2021-10-08 12:11 UTC by Deepshikhats

Fixes #15

2021-10-08 13:47 UTC, safaldas requested changes

2021-10-08 13:47 UTC, safaldas commented on client/src/components/user-card/user-card.js
> +    const OpenModal = () => setModal(true);
all functions must be camelcased

2021-10-08 13:47 UTC, safaldas commented on client/src/components/user-card/user-card.js
> +        setPopup(true);
if it is a single function u can set it in the onClick={() =>setPopup(true)}

2021-10-08 13:47 UTC, safaldas commented on client/src/components/user-card/user-card.js
> +            {cropmodal ? <div className='shadow-lg border border-primary m-6 w-680 rounded-lg h-auto'>
here u can use `{cropmodal && <YourComponent/>}` instead of the terinary operator. `{cropmodal ? <YourComponent/> : null }` && is prefered

2021-10-10 15:49 UTC, Deepshikhats commented
Fixes #15

2021-10-11 11:37 UTC, merged